[theme]
primaryColor = "#20C997"                # Mint/teal green
backgroundColor = "#F5F7FA"             # Light cream/white smoke
secondaryBackgroundColor = "#E0ECE4"    # Soft mint gray for sidebars/cards
textColor = "#212529"                   # Dark gray for high contrast
font = "sans serif"

[browser]
gatherUsageStats = false
